### ISSUE TITLE
Bug in Symbol structure definition

### ISSUE THREAD

**Issue by maxamel** [timpalpant/go-iex#11]
When fetching the /ref-data/symbols url from the web I get the response:
```
[{"symbol":"A","name":"Agilent Technologies Inc.","date":"2018-07-25","isEnabled":true,"type":"cs","iexId":"2"}, .....
```
However the Symbol structure in the project is defined as follows:
```
type Symbol struct {
	// Refers to the symbol represented in Nasdaq Integrated symbology (INET).
        **_Ticker string_**
	// Refers to the name of the company or security.
	Name string
	// Refers to the date the symbol reference data was generated.
	Date string
	// Will be true if the symbol is enabled for trading on IEX.
	IsEnabled bool
}
```
The ```Ticker``` field should be renamed to ```Symbol```, otherwise it isn't decoded with the JSON and effectively, gets left out of the response of the method ```GetSymbols()```. This is an important field as it is the identifier of every stock.

**Comment by timpalpant** [comment]
Fixed in #13, thanks for the detailed investigation and great report!
