### ISSUE TITLE
How to save the output to a json file?

### ISSUE THREAD

**Issue by devanshuDesai** [timpalpant/go-iex#6]
The library prints out the values the values in the terminal, but there does not seem to be a way to save the output as a txt/json file. Is there a way to do this?

**Comment by timpalpant** [comment]
This is not directly supported in the tool, but you can wrap it in a bash script to redirect the output to a file using your shell as demonstrated in the [README](https://github.com/timpalpant/go-iex#pcap2json):

```bash

#!/bin/bash
pcap2json < $1 > $2
```
