### ISSUE TITLE
Some entries not parsed correctly when running pcap2json

### ISSUE THREAD

**Issue by andrew-laughlin** [timpalpant/go-iex#8]
Thanks for the great library!

When running main.go against the IEX pcap [sample,](https://www.googleapis.com/download/storage/v1/b/iex/o/data%2Ffeeds%2F20180127%2F20180127_IEXTP1_TOPS1.6.pcap.gz?generation=1517101257197858&alt=media) some entries are not decoded to JSON correctly. The failed entries look like --> "WE2Bi5o3AroNFVpYSUVUICAgeEEPAAAAAAA="

Repro (on Windows)
` go run C:\Users\user\Downloads\Projects\go-iex\pcap2json\main.go < 20180127_IEXTP1_TOPS1.6.pcap > iex.json`

Also, it appears the output is truncated. For example, the last line in the output file is incomplete:
`{"MessageType":81,"Flags":64,"Timestamp":"2018-01-27T17:35:26.6146978Z","Symbol":"AYT","BidSize":0,"BidPrice":0,`

**Comment by timpalpant** [comment]
https://github.com/timpalpant/go-iex/pull/9/commits/8f3f9fa0ab5775b4f95260696f03854572646bb7 fixes the second issue.

I've confirmed the first issue as well, but haven't had a chance to investigate yet.

Thanks for the great error report!

**Comment by timpalpant** [comment]
https://github.com/timpalpant/go-iex/pull/10 fixes the first issue. These entries were `OfficialPriceMessage`, an unsupported message type that I either accidentally skipped or has since been added.

I made two changes:
1. To be more future-compatible, `pcap2json` will output unsupported messages as valid JSON, of the form:
```
{"MessageType": X, "Message": "... unparsed message bytes ..."}
```
It will also log a warning when encountering an unsupported messages.

2. Added support for `OfficialPriceMessages`. So these are now parsed and output:

```
$ go run pcap2json/main.go < ~/Downloads/20180127_IEXTP1_TOPS1.6.pcap | grep 'MessageType":88'
{"MessageType":88,"PriceType":81,"Timestamp":"2018-01-27T14:30:00.002535006Z","Symbol":"ZEXIT","OfficialPrice":9.99}
{"MessageType":88,"PriceType":81,"Timestamp":"2018-01-27T14:30:00.002584247Z","Symbol":"ZIEXT","OfficialPrice":0.99}
{"MessageType":88,"PriceType":81,"Timestamp":"2018-01-27T14:43:00.131848184Z","Symbol":"ZXIET","OfficialPrice":100}
{"MessageType":88,"PriceType":77,"Timestamp":"2018-01-27T17:00:00.009001766Z","Symbol":"ZIEXT","OfficialPrice":0.98}
{"MessageType":88,"PriceType":77,"Timestamp":"2018-01-27T17:05:00.499916237Z","Symbol":"ZEXIT","OfficialPrice":9.99}
{"MessageType":88,"PriceType":77,"Timestamp":"2018-01-27T17:12:48.179301249Z","Symbol":"ZXIET","OfficialPrice":99.98}
```

**Comment by andrew-laughlin** [comment]
Thanks for the quick response. I pulled master and ran it (on Windows 10) and get:

```
go run main.go < 20180127_IEXTP1_TOPS1.6.pcap > iex.json
# command-line-arguments
..\Projects\go-iex\pcap2json\main.go:41:63: msg.MessageType undefined (type *iextp.UnsupportedMessage has no field or method MessageType)

```

**Comment by timpalpant** [comment]
I'm having trouble reproducing that error with a clean checkout. Do you mind verifying the HEAD commit of your checkout?

```
$ git log | head
commit 12c42d27c339318497cb8124d4cc2cbcf7efedd0
Merge: adac837 49d8851
Author: Timothy Palpant <tim@palpant.us>
Date:   Thu May 17 22:45:58 2018 -0400

    Merge pull request #10 from timpalpant/fix_unk
    
    Fix pcap2json output if there are unsupported message type, add OfficialPriceMessage

commit 49d885133dfdba27d64e70d51d7f0880e1564362
```

You can also check the file `iextp/iextp.go` which should [have in it](https://github.com/timpalpant/go-iex/blob/master/iextp/iextp.go#L98):

```
$ grep -A 3 UnsupportedMessage iextp/iextp.go 
// UnsupportedMessage may be returned by a protocol for any
// message types it does not know how to decode.
type UnsupportedMessage struct {
	MessageType uint8
	Message     []byte
}
```

If those both look correct, I am not sure what's happening. Maybe try explicitly disabling the build cache with `go run -a ...`?

**Comment by andrew-laughlin** [comment]
I'm not having any luck. I deleted the repo and re-pulled. I verified the most recent commit, then ran with `-a`. iextp.go does contain the type, so I'm not sure why the error occurs. This is my first foray into Go. Version info: 

```
go version
go version go1.10.2 windows/amd64

```

Does it matter what directory the script is run from?

**Comment by andrew-laughlin** [comment]
I figured out where I went wrong. Updating the package corrected the issue. Thanks again for the help.

~ Andrew
